### ISSUE TITLE
预印本中的问题

### ISSUE THREAD

**Issue by 2023ComputBio** [luwei0917/DynamicBind#1]
你好，我对你们这篇工作非常好奇，有几个问题请教一下：
1. 蛋白特征用的是CA为节点做的，还额外加入了侧链torsion angle。我看你们的chi写的是5个，但是chi只有4个呀。是额外加了主链的角度吗？
2. 网络建图用的是Ca的KNN图，那么加入torsion angle有帮助吗？特别是对侧链motion的预测，文章似乎只给了一个例子，展示了能够handle侧链；是否有考虑使用PoseBusters（https://arxiv.org/abs/2308.05777）评估结合构象的物理合理性？
3. 模型部分和diffdock的高度重合 (创新部分应该是蛋白的diffusion部分)，但是Method部分似乎没有说清楚哪些是diffdock的，模型架构的新颖性具体是什么？
4. 如果我没有理解错，morph-like transformation指的是对残基骨架frame，侧链的delta (对齐的native构象和AF2预测构象的差)进行的diffusion吧？
5. 测试集上使用AF2预测的构象做测评，由于你们的方法考虑了骨架的movement，因此是work的。而其他刚性的方法在这个测试集上表现不好是正常的，有分析过口袋rmsd和预测的构象RMSD的相关性吗？是否用Holo结构测评传统方法和diffdock，这样可以有一个直观的upper limit。
6. AF2做结构预测的参数是？用AF2预测PDBBind的蛋白结构，口袋RMSD（口袋CA RMSD还是全原子的？）不会有很多大于RMSD的case吧？毕竟大部分结构都是它训练集里的，骨架是能够预测合理的，应该不会有这么大差异。
7. 建议测试集还是和训练集做一下序列一致性和小分子指纹相似性的去冗余，使用时间划分是很有可能导致测试集和训练集有高度重复。特别是MDT测试集包括的蛋白，可能PDBBind里都有类似的序列。如果包含在训练集中，那么恢复Holo结构对模型而言并不是难事，反而其他的方法因为无法变化骨架，性能有所下降。
非常有意思的工作，对药物设计帮助很大，我因为感兴趣所以问了这么多问题。如果有说的不对之处，请谅解和批评！
2023/08/25

**Comment by luwei0917** [comment]
感谢你的兴趣和提问。
1. chi5 exists for ARG.
https://github.com/biopython/biopython/blob/d416809344f1e345fbabbdaca4dd6dcf441e53bd/Bio/PDB/ic_data.py#L375
2. 有看到你发的文章，我们也计算了clash程度，DynamicBind（DyB）的构象合理性是还可以的，在文章以外我们还做了些操作（这个可以等我们完整代码公布了再细说)
3. 你理解的基本没错，模型框架基本follow了diffdock（其实diffdock也是基于torsional diffusion) 主要创新在数据集的构建，和训练时的采样设计。 另外就是你提到的 增加了蛋白的diffusion。
4. 是的。（但和传统完全随机不同的是，构象的变化是协同的。）
5.  holo结构评测结果我们留到了rebuttal的阶段，总的来说，holo作为input，相比diffdock有细微提升，但不显著。“口袋rmsd和预测的构象RMSD的相关性吗” ，构象RMSD你是指分子构象吧，这事倒好像是没直接测过。 有时间我可以看看。
6. 不是很明白’AF2做结构预测的参数是‘指的是什么， 我们就是用的默认AF2。 口袋RMSD是全原子。 印象中有一些RMSD还蛮大的。HSP90，因为他其实PDB库里面就有构象很大的变化。 AF2只能选其中一个。 
7. 这个我们的确有考虑。但其实这个模型不单单对于全新蛋白有价值（SETD2），对于见过的蛋白，但是配体分子不同，他能找到正确的对应构象其实也是有价值的。而在真实的药物筛选过程中，我们不一定知道最适合的蛋白构象应该是哪个。

欢迎更多的问题。如果有些更细节的不方便公开讨论，你也可以邮件问我。

**Comment by 2023ComputBio** [comment]
感谢你及时的回复，
1. 事实上，ARG的chi5的刚性还是很强的，他们结构预测的那帮人基本不考虑这个了。你们考虑的太细了，好多人估计都忘记还有chi5这个了，hhh。
2. 那篇文章不是我发的，我只是觉得机器学习那帮人纯粹为了刷指标，这些很有价值的东西他们都忽略了，学术不够严谨。clash这方面其实用OpenMM跑下能量极小化一般是够的。
3. diffdock和torsional diffusion本来就是同一个团队一起做出来的，他们就是三个人一个团队，每个人负责一小个部分，分期发paper；
4. 传统完全随机是指？类似RFDiffusion那种做DDPM的吗？用VE-SDE在delta value上做确实一定程度上能够保证结构的合理性，毕竟就是对变化做微扰嘛。但是构象协同变化是啥意思？
5. 考虑这个是有必要的，因为毕竟你们数据集的构象变化是有限的，具体你们的模型能够做到多大的构象变化，这个参考区间我个人认为是蛮重要的。
6. 就是说有没有用模板，有没有改动过AF2等等；
7. 这个我明白，能够做到Holo构象的诱导确实很fancy，但是如果你们投稿的是咱们领域的其他，不是顶会的话，这个估计会被很多人问和质疑吧，毕竟PDBBind的金标准基本数据集就是CASF2016，他们机器学习那帮人改成时间拆分的很难不让人误解。

最后还是感谢你的答复，我是北大的学生。以前本科是中大药学院的，你们文章几个作者中大药院的我都认识或者听过。你有意愿，可以合作一下。我也有做这块的课题~

**Comment by luwei0917** [comment]
好呀。 你说的几点都很有道理。 我们可以找时间电话或者视频再聊一下细节。 我手机号13912617999. 加个微信？
