### ISSUE TITLE
Error messages and pro_ema_inference_epoch138_model.pt not found

### ISSUE THREAD

**Issue by CLG68** [luwei0917/DynamicBind#13]
Hi,
I would like to compare DynamicBind with FlexPose.  However, I get some error messages when I try to run it.  One of it is:

Error: mkl-service + Intel(R) MKL: MKL_THREADING_LAYER=INTEL is incompatible with libgomp.so.1 library.
so I did:
export MKL_SERVICE_FORCE_INTEL=1 , which solved some of the related problems but I still get this error message.

The second problem is:
FileNotFoundError: [Errno 2] No such file or directory: '/media/christian/VS/VS/VS_DynamicBind/workdir/big_score_model_sanyueqi_with_time/pro_ema_inference_epoch138_model.pt'

The Workdir folder contains: ema_inference_epoch314_model.pt  & model_parameters.yml
pro_ema_inference_epoch138_model.pt is not in the workdir folder.  Is it supposed to be there in the workdir that we are downloading or is it created?

Best,
Christian

**Comment by CLG68** [comment]
I renamed ema_inference_epoch314_model.pt & model_parameters.yml to
pro_ema_inference_epoch138_model.pt.  Now, it gets through.  However, I'm not sure if it was a good thing to do if it was expected the real: pro_ema_inference_epoch138_model.pt..
Processing 1 structure just takes forever (90min/ligand).  It is using only 1 thread so I guess MKL does not work as it is supposed to be using multi-threading.  Probably MKL_THREADING_LAYER should have "GNU" instead of "INTEL" as value as I'm using an AMD cpu.
I also get:
Error initializing CUDA: CUDA_ERROR_NO_DEVICE (100) at /home/conda/feedstock_root/build_artifacts/openmm_1706892976221/work/platforms/cuda/src/CudaContext.cpp:91
I do not see why it would want to find something in /home/conda ... I'm using anaconda3, there is no conda folder in Home/ .
I activated the env dynamicbind and tested: torch.cuda.is_available() and I get "true" so there is no obvious problem.
Under env relax, there is no cuda installed.

Thanks for your help,
Christian

**Comment by Nobody-Zhang** [comment]
Umm, I guess it is due to the CUDA environment which is not set properly on the machine.
It is noticeable that this repo uses 2 environments, so if one of their CUDA are not set, it can cause this problem.
Meanwhile, when using the script to create the env, I met a problem which is similar to yours, and it is due to the reason that the  openmm version mismatched the CUDA version. In that case, I activated my "relax" env, and then changed the version to a older one. It works.

Hope these words were useful for ur problem...

**Comment by GanQiao1990** [comment]
i just cp ema_inference_epoch314_model.pt to pro_ema_inference_epoch138_model.pt in the same file. it worked.

**Comment by Nobody-Zhang** [comment]
> i just cp ema_inference_epoch314_model.pt to pro_ema_inference_epoch138_model.pt in the same file. it worked.

Well, you do seem to find the right solution to it : )

**Comment by CLG68** [comment]
Thank you very much for your help.  I will try again with your suggestion of downgrading to an older version
