### ISSUE TITLE
Results analysis

### ISSUE THREAD

**Issue by chemgirl97** [luwei0917/DynamicBind#14]
Hi, Thank you for your effors.

In the calculation using the files provided in this example, the results in the
1. none of the resulting values match in the files affinity_prediction.csv and complete_affinity_prediction.csv. What is the difference between the two files?

![aa](https://github.com/luwei0917/DynamicBind/assets/74895803/874ac584-cb7c-4d4c-b720-24dae99071f3)

2. is the ranking done by LDDT, does this mean that rank1 is better than rank2 or rank3 ...?

**Comment by luwei0917** [comment]
affinity_prediction give you a weighted average. ranking is done by LDDT plus a bit of predicted affinity. 
you can check the code for details.

**Comment by accg12** [comment]
Hello - should these affinity values be negative? When running DynamicBind with your test data as well as mine (with known ligand binders), I get all positive affinity values.
