### ISSUE TITLE
LM embeddings for complex did not have the right length for the protein

### ISSUE THREAD

**Issue by liyue9129** [luwei0917/DynamicBind#38]
Hi !
Great work !
I have encountered several issues during the docking process. And I am seeking to determine whether the issue originate from the protein structure or the ESM employed, and to pinpoint the exact nature of the problem.
`LM embeddings for complex did not have the right length for the protein`

![image](https://github.com/user-attachments/assets/ee8ad825-30a7-48a4-98a6-84d010e9da61)

Thank you !
best wishes!

**Comment by patjiang** [comment]
Hello! Rather than a screenshot of the code itself, could you also provide the associated stderr output? That is, if the code generates a print statement or a .out file, could you please show that as well?

From what I've seen with working in this package, I think this should not be an endemic issue, rather, this might happen sometimes in the "pseudo-dynamics" timesteps of the model-- that being said, I do believe that this issue might be moreso due to the structure rather than the esm embeddings. I hope this helps!

**Comment by liyue9129** [comment]
Thank you so much for your help !
The associated stderr output is as follows：
![image](https://github.com/user-attachments/assets/f398e274-849a-4517-9d86-818c01d3265f)
![image](https://github.com/user-attachments/assets/2b2d3c8b-0721-447d-b397-bd60d3510c5d)

Due to computer issues in the past few days resulting in data loss, I apologize for not being able to provide the specific PDB complex file. 
However, during my previous debugging, I found that the problem originated from using the ESM embeddings to generate protein features, as shown in the red box in the figure below. The first and second chains are fine, but the third and fourth chains only encode 37 and 32 amino acids, respectively.

![image](https://github.com/user-attachments/assets/baf773ac-1621-4343-b0ac-bb4be6a62f11)

Best wishes !

**Comment by patjiang** [comment]
Hello, 

Thank you for providing the associated issues; for context, do the third and fourth chains also expect 559 residues as well?

Also, are what args are you  passing into the top level argument?

I hope to continue to provide support!

**Comment by liyue9129** [comment]
Yes, the 3rd and 4th chains also have 559 amino acids.

`    command = [
        "python", "run_single_protein_inference.py",
        f"/public/home/user/complex_preparation/posebusters/{data_name}/{name}/{name}_protein.pdb",
        f"/public/home/user/complex_preparation/posebusters/{data_name}/{name}/{name}_ligand_smiles_to_csv.csv",
        "--savings_per_complex", "40",
        "--inference_steps", "20",
        "--header", f"{name}",
        "--device", "0",
        "--python", "/public/home/user/miniconda3/envs/dynamicbind/bin/python",
        "--relax_python", "/public/home/user/miniconda3/envs/relax/bin/python",
        "--result", f"/public/home/user/DLDock/DynamicBind/test/{data_name}",
    ]
、

**Comment by liyue9129** [comment]
Hi！
It is so nice of you to provide such a clear stack trace ！

I've tried to reproduce the issue and provide the ESM2 outputs.
To do so, I modified the path where preprocessed data is saved in run_single_protein_inference.py and found that the error no longer occurred.

Therefore, it is believed that when performing many protein-ligand docking tasks, saving all preprocessed data in a single folder might lead to confusion and inconsistencies.

Thus, it is suggested that adding a path prefix, data_pre_dir = f'{args.results}/{args.header}', before all data used in [run_single_protein_inference.py](https://github.com/luwei0917/DynamicBind/blob/main/run_single_protein_inference.py#L71): f"{data_pre_dir}/data".

I apologize for taking up your valuable time.

Best wishes!

**Comment by liyue9129** [comment]
Thank you for all your help！Have a good day!

**Comment by Kimi-Dai** [comment]
Hi！
I also encoutered into this problem. I've tried to modify the "truncation_seq_length" to 30000 but it doesn't work. Could you please give a more detailed solution to this problem? I don't quite understand what "modified the path where preprocessed data is saved in run_single_protein_inference.py"means. I also don't find file called "esm_output" in data/ 
Thanks!
