### ISSUE TITLE
error, while running

### ISSUE THREAD

**Issue by surendraphd** [luwei0917/DynamicBind#5]
Hi,
I am facing the following error, while running the job via command line.

**FileNotFoundError: [Errno 2] No such file or directory: '/home/medicina/Downloads/DynamicBind/workdir/big_score_model_sanyueqi_with_time/pro_ema_inference_epoch138_model.pt'**

my workdir contain only this file.

ema_inference_epoch314_model.pt

How to fix the issue.

(dynamicbind) medicina@medicina:~/Downloads/DynamicBind$ python run_single_protein_inference.py 1qg8_cleaned.pdb 1qg8_input.csv --savings_per_complex 40 --inference_steps 20 --header test  --python /home/medicina/anaconda3/envs/dynamicbind/bin/python --relax_python /home/medicina/anaconda3/envs/relax/bin/python
INFO:root:run_single_protein_inference.py 1qg8_cleaned.pdb 1qg8_input.csv --savings_per_complex 40 --inference_steps 20 --header test --python /home/medicina/anaconda3/envs/dynamicbind/bin/python --relax_python /home/medicina/anaconda3/envs/relax/bin/python
2023_12_31_19_07
--------------------------------

/home/medicina/Downloads/DynamicBind/run_single_protein_inference.py /home/medicina/Downloads/DynamicBind
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 59.60it/s]
hub dir /home/medicina/Downloads/DynamicBind/esm_models
Downloading: "https://dl.fbaipublicfiles.com/fair-esm/models/esm2_t33_650M_UR50D.pt" to /home/medicina/Downloads/DynamicBind/esm_models/checkpoints/esm2_t33_650M_UR50D.pt
Downloading: "https://dl.fbaipublicfiles.com/fair-esm/regression/esm2_t33_650M_UR50D-contact-regression.pt" to /home/medicina/Downloads/DynamicBind/esm_models/checkpoints/esm2_t33_650M_UR50D-contact-regression.pt
Transferred model to GPU
Read data/prepared_for_esm_test.fasta with 1 sequences
Processing 1 of 1 batches (1 sequences)
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [00:52<00:00,  3.80it/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 201/201 [01:04<00:00,  3.13it/s]
Reading molecules and generating local structures with RDKit
4it [00:00, 14.83it/s]
Reading language model embeddings.
Generating graphs for ligands and proteins
loading complexes: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00,  6.33it/s]
loading data from memory:  data/cache_torsion/limit0_INDEX_maxLigSizeNone_H0_recRad15.0_recMax24_esmEmbeddings3297976096/heterographs.pkl
Number of complexes:  4
radius protein: mean 27.280357360839844, std 0.0, max 27.280357360839844
radius molecule: mean 6.446958541870117, std 0.2975179851055145, max 6.782521724700928
distance protein-mol: mean 5.086441845492118e-08, std 2.719834313325009e-08, max 9.765030029029731e-08
rmsd matching: mean 0.0, std 0.0, max 0
Traceback (most recent call last):
  File "/home/medicina/Downloads/DynamicBind/inference.py", line 152, in <module>
    state_dict = torch.load(f'{args.model_dir}/{args.ckpt}', map_location=torch.device('cpu'))
  File "/home/medicina/anaconda3/envs/dynamicbind/lib/python3.10/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/medicina/anaconda3/envs/dynamicbind/lib/python3.10/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/medicina/anaconda3/envs/dynamicbind/lib/python3.10/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
**FileNotFoundError: [Errno 2] No such file or directory: '/home/medicina/Downloads/DynamicBind/workdir/big_score_model_sanyueqi_with_time/pro_ema_inference_epoch138_model.pt'
inference complete.**
0it [00:00, ?it/s]
final step structure relax complete.

Thanks in advance.

**Comment by Nobody-Zhang** [comment]
I tried to rename the file from "ema_inference_epoch314_model.pt" to "pro_ema_inference_epoch138_model.pt" ahh, and it seem to fix this problem.... Actually i donot think this is the right idea, but it works ahhh.

**Comment by Nobody-Zhang** [comment]
You can fix this problem by just adding "-p" in your command line. 
By referring to the file named "run_single_protein_inference.py", line 42, you can see why this arg fix it.

**Comment by arvindsemwal20** [comment]
Thanks it worked.

**Comment by yukisoya** [comment]
I also encountered the same error, so I executed the following command with an added "-p" option. 
`python run_single_protein_inference.py ./data/1qg8_cleaned.pdb ./data/1qg8_input.csv --savings_per_complex 40 --inference_steps 20 --header test --device 4 --python /path/to/.conda/envs/dynamicbind/bin/python --relax_python /path/to/.conda/envs/relax_for_dynamicbind/bin/python -p`

The output was as follows, but no output files were saved in the results/test directory. 
Could you please provide a solution?
---
/path/to/DynamicBind/run_single_protein_inference.py /path/to/DynamicBind
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 68.70it/s]
hub dir /path/to/DynamicBind/esm_models
/path/to/.conda/envs/dynamicbind/lib/python3.10/site-packages/torch/cuda/__init__.py:173: UserWarning: 
NVIDIA H100 80GB HBM3 with CUDA capability sm_90 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_61 sm_70 sm_75 sm_80 sm_86 compute_37.
If you want to use the NVIDIA H100 80GB HBM3 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
Transferred model to GPU
Read data/prepared_for_esm_test.fasta with 1 sequences
Processing 1 of 1 batches (1 sequences)
Reading molecules and generating local structures with RDKit
4it [00:00, 15.34it/s]
Reading language model embeddings.
Generating graphs for ligands and proteins
loading complexes: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00,  8.99it/s]
loading data from memory:  data/cache_torsion/limit0_INDEX_maxLigSizeNone_H0_recRad15.0_recMax24_esmEmbeddings3297976096/heterographs.pkl
Number of complexes:  4
radius protein: mean 27.280357360839844, std 0.0, max 27.280357360839844
radius molecule: mean 6.446958541870117, std 0.2975179851055145, max 6.782521724700928
distance protein-mol: mean 4.864434544060714e-08, std 2.4620504746053484e-08, max 9.081018248480177e-08
rmsd matching: mean 0.0, std 0.0, max 0
common t schedule [1.   0.95 0.9  0.85 0.8  0.75 0.7  0.65 0.6  0.55 0.5  0.45 0.4  0.35
 0.3  0.25 0.2  0.15 0.1  0.05]
Size of test dataset:  4
0it [00:00, ?it/s]Floating point exception (core dumped)
inference complete.
0it [00:00, ?it/s]
final step structure relax complete.
